"""Rebuild kb/views/ as a browsable per-module copy of the KB.

`kb/entries/` stays flat -- it is the source of truth and this script never
writes to it. `kb/views/` is a throwaway derived tree you regenerate whenever
you want to browse by module. It is gitignored and every run rebuilds it from
scratch, so an entry whose `module` changed lands in the new folder and leaves
no ghost behind in the old one.

Copies, not symlinks: symlinks need elevation or developer mode on Windows and
behave differently across filesystems, which is not worth it for a scratch
directory.

Usage (from the repo root)::

    python scripts/build_module_views.py
    python scripts/build_module_views.py --include-staging
    python scripts/build_module_views.py --group-by module/entry_type
    python scripts/build_module_views.py --dry-run
"""

from __future__ import annotations

import argparse
import shutil
import sys
from collections import Counter
from dataclasses import dataclass
from pathlib import Path

if __package__ in {None, ""}:  # allow `python scripts/build_module_views.py`
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from core.storage import read_frontmatter  # noqa: E402

# Written into the views root so a rebuild knows the directory is ours to
# delete. Without it, a typo in --views-dir could point rmtree at real data.
MARKER_NAME = ".generated-module-views"
MARKER_TEXT = "Generated by scripts/build_module_views.py. Safe to delete.\n"

UNKNOWN_GROUP = "_unknown"
# Reserved on Windows even with an extension; a module literally named "con"
# would otherwise produce an undeletable directory.
WINDOWS_RESERVED = {
    "con",
    "prn",
    "aux",
    "nul",
    *{f"com{digit}" for digit in range(1, 10)},
    *{f"lpt{digit}" for digit in range(1, 10)},
}
UNSAFE_CHARS = set('<>:"/\\|?*')


@dataclass
class SourceDir:
    """One directory to scan, and the filename suffix its copies get."""

    dirname: str
    suffix: str


@dataclass
class Skipped:
    path: Path
    reason: str


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Rebuild kb/views/ as a per-module copy of the KB entries",
    )
    parser.add_argument("--kb-root", type=Path, default=Path("kb"))
    parser.add_argument(
        "--views-dir",
        type=Path,
        default=None,
        help="output directory (default: <kb-root>/views)",
    )
    parser.add_argument(
        "--include-staging",
        action="store_true",
        help="also copy pending proposals from staging/, suffixed .pending.md",
    )
    parser.add_argument(
        "--group-by",
        choices=("module", "module/entry_type"),
        default="module",
        help="directory nesting (default: module)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="report what would be written without touching the filesystem",
    )
    args = parser.parse_args()

    kb_root: Path = args.kb_root
    views_dir: Path = args.views_dir if args.views_dir is not None else kb_root / "views"

    if not kb_root.is_dir():
        print(f"error: kb root is not a directory: {kb_root}", file=sys.stderr)
        return 2

    sources = [SourceDir("entries", ".md")]
    if args.include_staging:
        # A pending update keeps the published entry's id, so both copies would
        # otherwise collide on one filename in the same module folder.
        sources.append(SourceDir("staging", ".pending.md"))

    try:
        _check_views_dir_is_safe_to_replace(views_dir, kb_root)
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    plan: list[tuple[Path, Path]] = []
    skipped: list[Skipped] = []
    renamed_groups: dict[str, str] = {}

    for source in sources:
        source_dir = kb_root / source.dirname
        if not source_dir.is_dir():
            continue
        for entry_path in sorted(source_dir.glob("*.md")):
            try:
                metadata, _ = read_frontmatter(entry_path)
            except (OSError, ValueError) as exc:
                skipped.append(Skipped(entry_path, str(exc)))
                continue

            parts = [_group_name(metadata.get("module"), renamed_groups)]
            if args.group_by == "module/entry_type":
                parts.append(_group_name(metadata.get("entry_type"), renamed_groups))
            target = views_dir.joinpath(*parts) / f"{entry_path.stem}{source.suffix}"
            plan.append((entry_path, target))

    if not args.dry_run:
        _rebuild(views_dir, plan)

    _report(views_dir, plan, skipped, renamed_groups, dry_run=args.dry_run)
    return 0


def _check_views_dir_is_safe_to_replace(views_dir: Path, kb_root: Path) -> None:
    """Refuse to rmtree anything that is not an existing generated view tree."""
    resolved = views_dir.resolve()
    if resolved == kb_root.resolve() or resolved == Path.cwd().resolve():
        raise ValueError(f"refusing to use {views_dir} as the views directory")
    for protected in ("entries", "staging", "deprecated", "drafts", "research", "indexes"):
        protected_path = (kb_root / protected).resolve()
        if resolved == protected_path or protected_path in resolved.parents:
            raise ValueError(f"refusing to write views into {protected}/: {views_dir}")
    if not resolved.exists():
        return
    if not resolved.is_dir():
        raise ValueError(f"views path exists but is not a directory: {views_dir}")
    if any(resolved.iterdir()) and not (resolved / MARKER_NAME).is_file():
        raise ValueError(
            f"{views_dir} is not empty and has no {MARKER_NAME} marker, so it was not "
            "generated by this script; delete it yourself if you meant to replace it"
        )


def _group_name(raw: object, renamed: dict[str, str]) -> str:
    """Turn a frontmatter value into a directory name that is safe everywhere."""
    original = str(raw).strip() if raw is not None else ""
    if not original:
        return UNKNOWN_GROUP
    cleaned = "".join("_" if char in UNSAFE_CHARS or ord(char) < 32 else char for char in original)
    cleaned = cleaned.strip(" .")  # trailing dots/spaces are invalid on Windows
    if cleaned.lower() in WINDOWS_RESERVED:
        cleaned = f"{cleaned}_"
    if not cleaned:
        return UNKNOWN_GROUP
    if cleaned != original:
        renamed[original] = cleaned
    return cleaned


def _rebuild(views_dir: Path, plan: list[tuple[Path, Path]]) -> None:
    if views_dir.exists():
        shutil.rmtree(views_dir)
    views_dir.mkdir(parents=True)
    (views_dir / MARKER_NAME).write_text(MARKER_TEXT, encoding="utf-8")
    for entry_path, target in plan:
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(entry_path, target)


def _report(
    views_dir: Path,
    plan: list[tuple[Path, Path]],
    skipped: list[Skipped],
    renamed_groups: dict[str, str],
    *,
    dry_run: bool,
) -> None:
    counts = Counter(
        str(target.parent.relative_to(views_dir)).replace("\\", "/") for _, target in plan
    )
    verb = "would write" if dry_run else "wrote"
    print(f"{verb} {len(plan)} file(s) into {views_dir} across {len(counts)} group(s)")
    for group, count in sorted(counts.items()):
        print(f"  {group}: {count}")
    if renamed_groups:
        print("renamed for filesystem safety:")
        for original, cleaned in sorted(renamed_groups.items()):
            print(f"  {original!r} -> {cleaned}")
    if skipped:
        print(f"skipped {len(skipped)} unreadable file(s):")
        for item in skipped:
            print(f"  {item.path}: {item.reason}")


if __name__ == "__main__":
    raise SystemExit(main())
